/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActivityItemFiat struct {
	// The status of the fiat activity item
	Status string `json:"status,omitempty"`
	// The fiat currency of the activity item
	Currency string `json:"currency,omitempty"`
	// The amount of fiat currency exchanged
	Amount string `json:"amount,omitempty"`
	// The direction the fiat is moving
	Direction string `json:"direction,omitempty"`
	// The method used for fiat, if funded
	FundingMethod string `json:"fundingMethod,omitempty"`
	BankAccount *BankAccount `json:"bankAccount,omitempty"`
}
