/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Wallets struct {
	// The wallets of the user
	Items []Wallet `json:"items"`
	// The token for the next page of results, if available
	NextPageToken string `json:"nextPageToken,omitempty"`
}
