/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetCryptoPricesResponse struct {
	// The quoted prices
	Prices []Price `json:"prices"`
	// The current network fees
	NetworkFees []NetworkFee `json:"networkFees"`
}
