/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Price struct {
	// Crypto currency
	CryptoCurrency string `json:"cryptoCurrency,omitempty"`
	// Quoted fiat currency
	FiatCurrency string `json:"fiatCurrency,omitempty"`
	// Price
	Price string `json:"price,omitempty"`
}
