/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConnectWalletRequest struct {
	// The network address of the wallet
	Address string `json:"address"`
	// The type of wallet to authenticate
	Type_ string `json:"type"`
	// A name for the wallet
	Name string `json:"name,omitempty"`
}
