/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InitiateAchRequest struct {
	// The amount in fiat to be exchanged
	FiatAmount string `json:"fiatAmount"`
	// The crypto currency to be purchased
	CryptoCurrency string `json:"cryptoCurrency"`
	// The ID of the wallet to receive the crypto
	WalletId string `json:"walletId"`
	// The type of ACH request
	Type_ string `json:"type"`
}
