/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateUserRequest struct {
	// The first name of the user
	FirstName string `json:"firstName"`
	// The middle name of the user
	MiddleName string `json:"middleName,omitempty"`
	// The last name of the user
	LastName string `json:"lastName"`
	// The email of the user
	Email string `json:"email"`
	// The country of the user (Format: ISO 3166 alpha-2)
	Country string `json:"country"`
	// The phone number of the user (Format: E-164)
	Phone string `json:"phone"`
	// A boolean indicating the user has accepted the terms
	AcceptedTerms bool `json:"acceptedTerms"`
}
