/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AuthResponse struct {
	// The authenticated Bearer token
	SessionJwt string `json:"sessionJwt"`
	UserMask *UserMask `json:"userMask,omitempty"`
	User *User `json:"user,omitempty"`
}
