/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Payroll struct {
	// The time the payroll connection was created
	CreateTime string `json:"createTime,omitempty"`
	// The time the payroll connection was last updated
	UpdateTime string `json:"updateTime,omitempty"`
	// The provider for the payroll
	Provider string `json:"provider,omitempty"`
	// The amount being distributed from this payroll
	Distribution string `json:"distribution,omitempty"`
}
