/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SendSmsOtpResponse struct {
	// The ID of the phone number
	PhoneId string `json:"phoneId"`
	// The last 4 digits of the phone number
	PhoneMask string `json:"phoneMask,omitempty"`
}
