/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AuthenticateSmsOtpRequest struct {
	// The OTP to authenticate
	Otp string `json:"otp"`
	// The phone identifier to authenticate
	PhoneId string `json:"phoneId"`
}
