/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateClientSessionRequest struct {
	// The wallet address that will be used to authenticate
	SigningAddress string `json:"signingAddress"`
	// The type of wallet to authenticate
	SigningType string `json:"signingType"`
	// The wallet address that will be used as the deposit target. If not provided, the signing address will be used
	DepositAddress string `json:"depositAddress,omitempty"`
}
