/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ClientSession struct {
	// The session ID
	Id string `json:"id,omitempty"`
	// The time the session was created
	CreateTime string `json:"createTime,omitempty"`
	// The time the session was last updated
	UpdateTime string `json:"updateTime,omitempty"`
	// The address of the signing wallet
	SigningAddress string `json:"signingAddress,omitempty"`
	// The type of wallet to authenticate
	SigningType string `json:"signingType,omitempty"`
	// The address of the deposit wallet
	DepositAddress string `json:"depositAddress,omitempty"`
	// The type of wallet to authenticate
	DepositType string `json:"depositType,omitempty"`
	UserMask *UserMask `json:"userMask,omitempty"`
	// The user's session JWT
	SessionJwt string `json:"sessionJwt,omitempty"`
}
