/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Webhook struct {
	// The unique identifier of the webhook
	Id string `json:"id"`
	// The time the webhook was created
	CreateTime string `json:"createTime"`
	// The time the webhook was last updated
	UpdateTime string `json:"updateTime"`
	// The name of the webhook
	Name string `json:"name,omitempty"`
	Events []string `json:"events"`
	// The secret of the webhook. This is only returned here when creating a webhook.
	Secret string `json:"secret,omitempty"`
}
