/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NetworkFee struct {
	// Crypto currency
	CryptoCurrency string `json:"cryptoCurrency,omitempty"`
	// Fee amount in crypto currency
	CryptoFee string `json:"cryptoFee,omitempty"`
	// Quoted fiat currency
	FiatCurrency string `json:"fiatCurrency,omitempty"`
	// Fee amount in fiat currency
	FiatFee string `json:"fiatFee,omitempty"`
}
