/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModelError struct {
	// Error message
	Message string `json:"message,omitempty"`
	// Error creation time
	CreateTime string `json:"createTime,omitempty"`
	// Error code
	Code string `json:"code,omitempty"`
	// Error data
	Data *interface{} `json:"data,omitempty"`
}
