/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Kyc struct {
	// The time the KYC was created
	CreateTime string `json:"createTime,omitempty"`
	// The time the KYC was last updated
	UpdateTime string `json:"updateTime,omitempty"`
	// The overall status of the KYC verification
	Status string `json:"status,omitempty"`
	// The result of the KYC address verification
	AddressResult string `json:"addressResult,omitempty"`
	// The result of the KYC date of birth verification
	DobResult string `json:"dobResult,omitempty"`
	// The result of the KYC fraud verification
	FraudResult string `json:"fraudResult,omitempty"`
	// The result of the KYC identity documentation verification
	IdvResult string `json:"idvResult,omitempty"`
}
