/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Wallet struct {
	// The unique identifier of the wallet
	Id string `json:"id"`
	// The time the wallet was created
	CreateTime string `json:"createTime"`
	// The time the wallet was last updated
	UpdateTime string `json:"updateTime"`
	// The address of the wallet
	Address string `json:"address"`
	// The nickname of the wallet
	Name string `json:"name,omitempty"`
	// The type of wallet to authenticate
	Type_ string `json:"type"`
}
