/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SubmitKycRequest struct {
	// The date of birth of the user (Format: YYYY-MM-DD)
	DateOfBirth string `json:"dateOfBirth"`
	// The type of ID
	IdType string `json:"idType"`
	// The number of ID
	IdNumber string `json:"idNumber"`
	// The first address line of the user
	Line1 string `json:"line1"`
	// The second address line of the user
	Line2 string `json:"line2,omitempty"`
	// The city of the user's address
	City string `json:"city"`
	// The state of the user's address (Format: 2-Letter state abbreviation. ex: CA)
	State string `json:"state"`
	// The postal code of the user's address
	PostalCode string `json:"postalCode"`
	// The nationality of the user
	Nationality string `json:"nationality,omitempty"`
	// The occupation of the user
	Occupation string `json:"occupation,omitempty"`
}
