/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActivityItemCrypto struct {
	// The status of the crypto activity item
	Status string `json:"status,omitempty"`
	// The crypto currency acquired for the activity item
	Currency string `json:"currency,omitempty"`
	Wallet *Wallet `json:"wallet,omitempty"`
	// The direction the crypto is moving
	Direction string `json:"direction,omitempty"`
	// The amount of crypto currency acquired
	Amount string `json:"amount,omitempty"`
	// The price of a single unit of the crypto currency; specified in the fiat currency
	Price string `json:"price,omitempty"`
	// The network fee to execute the crypto transaction; specified in the fiat currency
	NetworkFee string `json:"networkFee,omitempty"`
	// The Ratio fee to execute the crypto transaction; specified in the fiat currency
	RatioFee string `json:"ratioFee,omitempty"`
	// The on-chain transaction hash of the activity item
	TransactionHash string `json:"transactionHash,omitempty"`
}
