/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RequestBankUpdateLinkRequest struct {
	// A URI indicating the destination after completing the OAuth authentication Link flow. Must be an https URI that contains no query parameters. Should not be set if using androidPackageName
	RedirectUri string `json:"redirectUri,omitempty"`
	// The name of your app's Android package. Should not be set if using redirectUri
	AndroidPackageName string `json:"androidPackageName,omitempty"`
}
