/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActivityItem struct {
	// The unique identifier of the allocation
	Id string `json:"id,omitempty"`
	// The time the allocation was created
	CreateTime string `json:"createTime,omitempty"`
	// The time the allocation was last updated
	UpdateTime string `json:"updateTime,omitempty"`
	Fiat *ActivityItemFiat `json:"fiat,omitempty"`
	Crypto *ActivityItemCrypto `json:"crypto,omitempty"`
	// (Optional) Additional metadata of the activity item
	Metadata *interface{} `json:"metadata,omitempty"`
}
