/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddUnverifiedCryptoWalletRequest struct {
	// The wallet address to authenticate
	WalletAddress string `json:"walletAddress"`
	// The type of wallet to authenticate
	WalletType string `json:"walletType"`
}
