/*
 * Ratio API
 *
 * API endpoints and models for using the Ratio service
 *
 * API version: 1.0.0
 * Contact: support@ratio.me
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IdvResponse struct {
	// The status of the user's identity verification
	Status string `json:"status,omitempty"`
	// The URL to provide the user to complete identity verification
	Url string `json:"url,omitempty"`
}
