const About = () => {
    return (
        <div className="about content">
            <span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At, in voluptatum expedita architecto iste deserunt et accusantium quam optio tempora quo cum temporibus excepturi est facere a eligendi repellendus id.</span><span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At, in voluptatum expedita architecto iste deserunt et accusantium quam optio tempora quo cum temporibus excepturi est facere a eligendi repellendus id.</span><span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At, in voluptatum expedita architecto iste deserunt et accusantium quam optio tempora quo cum temporibus excepturi est facere a eligendi repellendus id.</span><span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At, in voluptatum expedita architecto iste deserunt et accusantium quam optio tempora quo cum temporibus excepturi est facere a eligendi repellendus id.</span><span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At, in voluptatum expedita architecto iste deserunt et accusantium quam optio tempora quo cum temporibus excepturi est facere a eligendi repellendus id.</span><span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At, in voluptatum expedita architecto iste deserunt et accusantium quam optio tempora quo cum temporibus excepturi est facere a eligendi repellendus id.</span>
            <span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At, in voluptatum expedita architecto iste deserunt et accusantium quam optio tempora quo cum temporibus excepturi est facere a eligendi repellendus id.</span><span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At, in voluptatum expedita architecto iste deserunt et accusantium quam optio tempora quo cum temporibus excepturi est facere a eligendi repellendus id.</span><span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At, in voluptatum expedita architecto iste deserunt et accusantium quam optio tempora quo cum temporibus excepturi est facere a eligendi repellendus id.</span><span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At, in voluptatum expedita architecto iste deserunt et accusantium quam optio tempora quo cum temporibus excepturi est facere a eligendi repellendus id.</span><span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At, in voluptatum expedita architecto iste deserunt et accusantium quam optio tempora quo cum temporibus excepturi est facere a eligendi repellendus id.</span><span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At, in voluptatum expedita architecto iste deserunt et accusantium quam optio tempora quo cum temporibus excepturi est facere a eligendi repellendus id.</span>
        </div>
     );
}
 
export default About;